### ISSUE TITLE
LCD Product Link

### ISSUE THREAD

**Issue by domdfcoding** [MatthewPageUK/pico_desktop_penholder#1]
Hi,

In the README you've linked to a round LCD, but the heading says "square" and the one in the photos looks square. Presumably you've included the wrong link? Do you know which LCD you used?

Thanks

**Comment by MatthewPageUK** [comment]
Thanks, I've updated the link to the correct square display
https://thepihut.com/products/1-54-spi-colour-square-lcd-240x240-breakout

**Comment by MatthewPageUK** [comment]
Ooops. wrong one again...
https://thepihut.com/products/1-3-spi-colour-lcd-240x240-breakout
